---
name: "Filename Provider"
guid: "0a35f534-abfa-4b67-bdd1-213d8dc7a0d0"
version: "1.0.0.0"
targetAbi: "10.11.6.0"
framework: "net9.0"
overview: "Metadata Provider that only uses the filename"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "Metadata"
owner: "Marcel"
artifacts:
- "Jellyfin.Plugin.Template.dll"
changelog: >
  changelog
